### ISSUE TITLE
ffprobe issue

### ISSUE THREAD

**Issue by will46616** [sigsep/sigsep-mus-db#80]
python test.py 
Traceback (most recent call last):
  File "/home3/will/BandSplitRNN-Pytorch-main/src/tt/test.py", line 158, in <module>
    mus = musdb.DB(root='/home3/will/musdb18',subsets='train')
  File "/home3/will/anaconda3/envs/MUSDB2/lib/python3.9/site-packages/musdb/__init__.py", line 118, in __init__
    self.tracks = self.load_mus_tracks(subsets=subsets, split=split)
  File "/home3/will/anaconda3/envs/MUSDB2/lib/python3.9/site-packages/musdb/__init__.py", line 265, in load_mus_tracks
    track = MultiTrack(
  File "/home3/will/anaconda3/envs/MUSDB2/lib/python3.9/site-packages/musdb/audio_classes.py", line 133, in __init__
    super(MultiTrack, self).__init__(path=path, *args, **kwargs)
  File "/home3/will/anaconda3/envs/MUSDB2/lib/python3.9/site-packages/musdb/audio_classes.py", line 52, in __init__
    self.info = stempeg.Info(self.path)
  File "/home3/will/anaconda3/envs/MUSDB2/lib/python3.9/site-packages/stempeg/read.py", line 328, in __init__
    self.info = ffmpeg.probe(filename)
  File "/home3/will/anaconda3/envs/MUSDB2/lib/python3.9/site-packages/ffmpeg/_probe.py", line 23, in probe
    raise Error('ffprobe', out, err)
ffmpeg._run.Error: ffprobe error (see stderr output for detail)

Hi, I have already installed ffmpeg and musdb, but it seems to have error while setting up musdb.

**Comment by faroit** [comment]
How did you install ffmpeg? Check the path using `which ffprobe`

**Comment by will46616** [comment]
I've checked my ffmpeg. I think my ffmpeg version is too new, the library of virtual environment needs libopenh264.so.5 to read the files.  It's all good now, but I'm not sure if there are any other problems with it.
